C_FILE += $(SROUCE)/util/tools/dos_endian.c \
			$(SROUCE)/util/tools/dos_string.c 			

C_OBJ_FILE += dos_endian.$(SUFFIX) \
				dos_string.$(SUFFIX)

dos_endian.$(SUFFIX) :
	$(C_COMPILE) $(SROUCE)/util/tools/dos_endian.c
	
dos_string.$(SUFFIX) :
	$(C_COMPILE) $(SROUCE)/util/tools/dos_string.c